// Sprite rendering: string-grid pixel art → cached offscreen canvases.
// DOM module (uses document.createElement) — never import from tests.

export const PALETTE = {
  K: '#1a1a24', // outline black
  W: '#ffffff',
  L: '#c8d0d8', // light grey
  E: '#9098a0', // grey
  e: '#5a6068', // dark grey
  R: '#d83838', // red
  r: '#982020', // dark red
  O: '#e88028', // orange
  Y: '#f8d020', // yellow
  y: '#fff8a8', // pale yellow
  G: '#38a048', // green
  g: '#1f7030', // dark green
  C: '#58b8e8', // sky blue
  B: '#3858d8', // blue
  b: '#243898', // dark blue
  T: '#d8a868', // tan
  t: '#a87840', // dark tan
  N: '#7a4a22', // brown
  n: '#4e2d12', // dark brown
  S: '#f8c890', // skin
  s: '#d89860', // skin shadow
  P: '#9858c8', // purple
  F: '#c89030', // lion/bear gold
  f: '#8a5e1a', // dark gold
};

// Background themes per world. Drawn procedurally in game.js.
export const THEMES = {
  fields:     { sky: '#5c94fc', hillFar: '#8cc850', hillNear: '#58a838', cloud: '#ffffff' },
  wilderness: { sky: '#d8a050', hillFar: '#b07838', hillNear: '#8a5828', cloud: '#f0e0c0' },
  valley:     { sky: '#6878a8', hillFar: '#586890', hillNear: '#404e70', cloud: '#c0c8d8' },
};

const cache = new Map(); // name -> {canvas, flipped, w, h}

function buildSprite(name, rows) {
  const h = rows.length;
  const w = rows[0].length;
  for (const r of rows) {
    if (r.length !== w) throw new Error(`ragged sprite: ${name}`);
  }
  const canvas = document.createElement('canvas');
  canvas.width = w; canvas.height = h;
  const ctx = canvas.getContext('2d');
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const ch = rows[y][x];
      if (ch === '.') continue;
      const color = PALETTE[ch];
      if (!color) throw new Error(`sprite ${name}: unknown palette char "${ch}"`);
      ctx.fillStyle = color;
      ctx.fillRect(x, y, 1, 1);
    }
  }
  const flipped = document.createElement('canvas');
  flipped.width = w; flipped.height = h;
  const fctx = flipped.getContext('2d');
  fctx.translate(w, 0); fctx.scale(-1, 1);
  fctx.drawImage(canvas, 0, 0);
  return { canvas, flipped, w, h };
}

// Call once at startup (from main.js) before any drawSprite call.
export function initSprites() {
  for (const [name, rows] of Object.entries(SPRITES)) {
    cache.set(name, buildSprite(name, rows));
  }
}

// Draw sprite by name at integer pixel position. flip mirrors horizontally.
export function drawSprite(ctx, name, x, y, { flip = false, scale = 1 } = {}) {
  const s = cache.get(name);
  if (!s) throw new Error(`unknown sprite: ${name}`);
  ctx.drawImage(flip ? s.flipped : s.canvas,
    Math.round(x), Math.round(y), s.w * scale, s.h * scale);
}

export function spriteSize(name) {
  const s = cache.get(name);
  return { w: s.w, h: s.h };
}

const SPRITES = {
  // ---- TILES (16x16) ------------------------------------------------
  tile_grass: [
    'GGGGGGGGGGGGGGGG',
    'GgGGGgGGGGgGGGgG',
    'gggggggggggggggg',
    'NNtNNNNtNNNNtNNN',
    'NtNNNtNNNtNNNNtN',
    'NNNNtNNNNNtNNNNN',
    'NnNNNNtNNNNNtNnN',
    'NNNtNNNNtNNNNNNN',
    'NtNNNNNNNNtNNNtN',
    'NNNNtNNtNNNNNNNN',
    'NnNNNNNNNNtNNnNN',
    'NNNtNNNtNNNNNNNN',
    'NNNNNNNNNNNtNNNN',
    'NnNNtNNNNNNNNNnN',
    'NNNNNNNtNNNNNNNN',
    'nnnnnnnnnnnnnnnn',
  ],
  tile_stone: [
    'LLLLLLLLELLLLLLL',
    'LEEEEEEEKEEEEEEL',
    'LELLLLLEKELLLLEL',
    'LELLLLLEKELLLLEL',
    'LELLLLLEKELLLLEL',
    'LEEEEEEEKEEEEEEL',
    'KKKKKKKKKKKKKKKK',
    'LEEEKEEEEEEKEEEL',
    'LELLEKLLLLEKLLEL',
    'LELLEKLLLLEKLLEL',
    'LELLEKLLLLEKLLEL',
    'LEEEKEEEEEEKEEEL',
    'KKKKKKKKKKKKKKKK',
    'LEEEEEEEKEEEEEEL',
    'LELLLLLEKELLLLEL',
    'eeeeeeeeeeeeeeee',
  ],
  tile_brick: [
    'TTTTTTTKTTTTTTTK',
    'TttttttKtttttttK',
    'TttttttKtttttttK',
    'KKKKKKKKKKKKKKKK',
    'TTTKTTTTTTTKTTTT',
    'TttKtttttttKtttt',
    'TttKtttttttKtttt',
    'KKKKKKKKKKKKKKKK',
    'TTTTTTTKTTTTTTTK',
    'TttttttKtttttttK',
    'TttttttKtttttttK',
    'KKKKKKKKKKKKKKKK',
    'TTTKTTTTTTTKTTTT',
    'TttKtttttttKtttt',
    'TttKtttttttKtttt',
    'KKKKKKKKKKKKKKKK',
  ],
  tile_blessing: [ // '?' block: gold with white dove mark
    'YYYYYYYYYYYYYYYY',
    'YyyyyyyyyyyyyyOY',
    'YyOOyyyyyyyyOyOY',
    'YyOyyyyWyyyyyyOY',
    'YyyyyyWWWyyyyyOY',
    'YyyyWWWWWWWyyyOY',
    'YyyyyWWWWWyyyyOY',
    'YyyyyyWWWWWyyyOY',
    'YyyyyyyWWyyyyyOY',
    'YyyyyyyWWyyyyyOY',
    'YyyyyyyyyyyyyyOY',
    'YyyyyyyWWyyyyyOY',
    'YyyyyyyWWyyyyyOY',
    'YyOyyyyyyyyyOyOY',
    'YyOOOOOOOOOOOOOY',
    'OOOOOOOOOOOOOOOO',
  ],
  tile_used: [
    'EEEEEEEEEEEEEEEE',
    'ELLLLLLLLLLLLLeE',
    'ELeeLLLLLLLLeLeE',
    'ELeLLLLLLLLLLLeE',
    'ELLLLLLLLLLLLLeE',
    'ELLLLLLLLLLLLLeE',
    'ELLLLLLLLLLLLLeE',
    'ELLLLLLLLLLLLLeE',
    'ELLLLLLLLLLLLLeE',
    'ELLLLLLLLLLLLLeE',
    'ELLLLLLLLLLLLLeE',
    'ELLLLLLLLLLLLLeE',
    'ELLLLLLLLLLLLLeE',
    'ELeLLLLLLLLLeLeE',
    'ELeeeeeeeeeeeeeE',
    'eeeeeeeeeeeeeeee',
  ],
  tile_platform: [ // one-way wooden platform (only top 6 rows visible)
    'TTTTTTTTTTTTTTTT',
    'tNtNtNtNtNtNtNtN',
    'NNNNNNNNNNNNNNNN',
    'nKnnKnnnKnnKnnKn',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  tile_thorns: [
    '................',
    '....K......K....',
    '...KgK....KgK...',
    '...KgK.K..KgK...',
    '..KgGgKgK.KgGgK.',
    '..KgGgKgKKgGgK..',
    '.KgGGgKgKgGGgK..',
    '.KgGGgGgGgGGgK..',
    'KgGGGgGgGgGGGgK.',
    'KgGGGGgGgGGGGgK.',
    'KgGGGGGgGGGGGgKK',
    'KgGGGGGGGGGGGggK',
    'KggGGGGGGGGGgggK',
    'KgggggggggggggK.',
    '.KKKKKKKKKKKKK..',
    '................',
  ],
  // ---- PLAYER: David (16x16, drawn facing RIGHT) ---------------------
  david_idle: [
    '................',
    '.....NNNNN......',
    '....NNNNNNN.....',
    '....NSSSSSN.....',
    '....NSKSSKS.....',
    '....NSSSSSS.....',
    '.....SSSSS......',
    '.....TTTTT......',
    '....TTTBTTT.....',
    '....TTTBTTT.....',
    '....STTBTTS.....',
    '....STTTTTS.....',
    '.....TTTTT......',
    '.....ss.ss......',
    '.....nn.nn......',
    '................',
  ],
  david_run1: [
    '................',
    '.....NNNNN......',
    '....NNNNNNN.....',
    '....NSSSSSN.....',
    '....NSKSSKS.....',
    '....NSSSSSS.....',
    '.....SSSSS......',
    '.....TTTTT......',
    '....TTTBTTT.....',
    '....TTTBTTT.....',
    '....STTBTTS.....',
    '....STTTTTS.....',
    '.....TTTTT......',
    '....ss...ss.....',
    '....nn...nn.....',
    '................',
  ],
  david_run2: [
    '................',
    '.....NNNNN......',
    '....NNNNNNN.....',
    '....NSSSSSN.....',
    '....NSKSSKS.....',
    '....NSSSSSS.....',
    '.....SSSSS......',
    '.....TTTTT......',
    '....TTTBTTT.....',
    '....TTTBTTT.....',
    '....STTBTTS.....',
    '....STTTTTS.....',
    '.....TTTTT......',
    '......sss.......',
    '......nnn.......',
    '................',
  ],
  david_jump: [
    '................',
    '.....NNNNN......',
    '....NNNNNNN.....',
    '....NSSSSSN.....',
    '....NSKSSKS.....',
    '....NSSSSSS.....',
    '.....SSSSS......',
    '....STTTTTS.....',
    '...STTTBTTTS....',
    '....TTTBTTT.....',
    '....TTTBTTT.....',
    '.....TTTTT......',
    '.....TTTTT......',
    '.....ssss.......',
    '.....nn.........',
    '................',
  ],
  // ---- ITEMS ----------------------------------------------------------
  manna: [ // golden wafer (16x16)
    '................',
    '................',
    '................',
    '................',
    '.....KKKKKK.....',
    '....KyyyyyyK....',
    '...KyyWWyyyyK...',
    '...KyYYYYYyyK...',
    '...KyYYYYYYyK...',
    '...KyyYYYYyyK...',
    '....KyyyyyyK....',
    '.....KKKKKK.....',
    '................',
    '................',
    '................',
    '................',
  ],
  scroll: [ // parchment scroll (16x16)
    '................',
    '................',
    '................',
    '...KKKKKKKKKK...',
    '..KWWWWWWWWWWK..',
    '..KWnnnnnnnnWK..',
    '..KWWWWWWWWWWK..',
    '..KWnnnnnnnnWK..',
    '..KWWWWWWWWWWK..',
    '..KWnnnnnnnnWK..',
    '..KWWWWWWWWWWK..',
    '...KKKKKKKKKK...',
    '................',
    '................',
    '................',
    '................',
  ],
  bread: [ // health loaf (16x16)
    '................',
    '................',
    '................',
    '................',
    '................',
    '.....KKKKKK.....',
    '....KTTTTTTK....',
    '...KTTtTTtTTK...',
    '...KTTTTTTTTK...',
    '...KtTTtTTtTK...',
    '....KttttttK....',
    '.....KKKKKK.....',
    '................',
    '................',
    '................',
    '................',
  ],
  sling: [ // sling power-up (16x16)
    '................',
    '................',
    '................',
    '....K......K....',
    '....NK....KN....',
    '.....NK..KN.....',
    '......NKKN......',
    '......KNNK......',
    '......KNNK......',
    '.....KNNNNK.....',
    '.....KNNNNK.....',
    '......KNNK......',
    '.......KK.......',
    '................',
    '................',
    '................',
  ],
  stone: [ // thrown sling stone (6x6)
    '.KKKK.',
    'KLLLEK',
    'KLLEEK',
    'KLEEEK',
    'KEEEeK',
    '.KKKK.',
  ],
  heart: [ // HUD heart (8x8)
    '.KK..KK.',
    'KRRKKRRK',
    'KRRRRRRK',
    'KRRRRRRK',
    '.KRRRRK.',
    '..KRRK..',
    '...KK...',
    '........',
  ],
  heart_empty: [ // HUD empty heart (8x8)
    '.KK..KK.',
    'KLLKKLLK',
    'KLLLLLLK',
    'KLLLLLLK',
    '.KLLLLK.',
    '..KLLK..',
    '...KK...',
    '........',
  ],
  // ---- LEVEL FURNITURE -------------------------------------------------
  gate: [ // goal: stone archway with golden light (16x32)
    '....KKKKKKKK....',
    '..KKLLLLLLLLKK..',
    '.KLLLEELLEELLLK.',
    'KLLEKKKKKKKKELLK',
    'KLEK........KELK',
    'KLEK...yy...KELK',
    'KLEK..yYYy..KELK',
    'KLEK..yYYy..KELK',
    'KLEK...yy...KELK',
    'KLEK........KELK',
    'KLEK...yy...KELK',
    'KLEK..yYYy..KELK',
    'KLEK..yYYy..KELK',
    'KLEK...yy...KELK',
    'KLEK........KELK',
    'KLEK...yy...KELK',
    'KLEK..yYYy..KELK',
    'KLEK..yYYy..KELK',
    'KLEK...yy...KELK',
    'KLEK........KELK',
    'KLEK...yy...KELK',
    'KLEK..yYYy..KELK',
    'KLEK..yYYy..KELK',
    'KLEK...yy...KELK',
    'KLEK........KELK',
    'KLEK........KELK',
    'KLEK........KELK',
    'KLEK........KELK',
    'KLEK........KELK',
    'KLEK........KELK',
    'KLEK........KELK',
    'eeee........eeee',
  ],
  altar_off: [ // checkpoint altar, inactive (16x16)
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '....KKKKKKKK....',
    '...KLLELLELLK...',
    '...KLELLELLLK...',
    '....KKKKKKKK....',
    '.....KLLEK......',
    '.....KLELK......',
    '....KKKKKKKK....',
    '...KLLLELLLLK...',
    '..KKKKKKKKKKKK..',
  ],
  altar_on: [ // checkpoint altar, lit (16x16)
    '................',
    '................',
    '.......Y........',
    '......YOY.......',
    '......YOY.......',
    '.....YOROY......',
    '......YRY.......',
    '....KKKKKKKK....',
    '...KLLELLELLK...',
    '...KLELLELLLK...',
    '....KKKKKKKK....',
    '.....KLLEK......',
    '.....KLELK......',
    '....KKKKKKKK....',
    '...KLLLELLLLK...',
    '..KKKKKKKKKKKK..',
  ],
  // ---- EFFECTS ---------------------------------------------------------
  puff: [ // defeat/collect star puff (16x16)
    '................',
    '.......W........',
    '.......W........',
    '...W.......W....',
    '....W..W..W.....',
    '................',
    '.W....WWW....W..',
    '......WWW.......',
    '.W....WWW....W..',
    '................',
    '....W..W..W.....',
    '...W.......W....',
    '.......W........',
    '.......W........',
    '................',
    '................',
  ],
  // ---- ENEMIES (16x16, drawn facing RIGHT) -----------------------------
  scorpion_1: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '..KK............',
    '.KrrK...........',
    '.KrrK..........K',
    '..KrK.........K.',
    '...K..KKKKKK.K..',
    '..K.KrRRRRRrKK..',
    '..KKrRRRRRRRrK..',
    '..KrRRKRRKRRrK..',
    '...KKKKKKKKKK...',
    '...K..K..K..K...',
    '................',
  ],
  scorpion_2: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '..KK............',
    '.KrrK...........',
    '.KrrK..........K',
    '..KrK.........K.',
    '...K..KKKKKK.K..',
    '..K.KrRRRRRrKK..',
    '..KKrRRRRRRRrK..',
    '..KrRRKRRKRRrK..',
    '...KKKKKKKKKK...',
    '..K..K..K..K....',
    '................',
  ],
  serpent_1: [
    '................',
    '................',
    '................',
    '....KKK.........',
    '...KGGGK........',
    '...KGKGKK.......',
    '...KGGGGGK......',
    '....KKKGGK......',
    '......KGGK......',
    '..KKKKGGGK......',
    '.KGGGGGGGK......',
    '.KGgGgGgGGKKK...',
    '..KGGGGGGGGGgK..',
    '...KKKKKKKKKK...',
    '................',
    '................',
  ],
  serpent_2: [
    '................',
    '................',
    '................',
    '....KKK.........',
    '...KGGGK........',
    '...KGKGKK.RR....',
    '...KGGGGGK......',
    '....KKKGGK......',
    '......KGGK......',
    '..KKKKGGGK......',
    '.KGGGGGGGK......',
    '.KGgGgGgGGKKK...',
    '..KGGGGGGGGGgK..',
    '...KKKKKKKKKK...',
    '................',
    '................',
  ],
  raven_1: [
    '................',
    '................',
    '....K.....K.....',
    '...KKK...KKK....',
    '...KKKK.KKKK....',
    '....KKKKKKK.....',
    '.....KKKKKKKO...',
    '....KKKKWKKK....',
    '....KKKKKKKK....',
    '.....KKKKKK.....',
    '......KKKK......',
    '.......KK.......',
    '................',
    '................',
    '................',
    '................',
  ],
  raven_2: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '.....KKKKKK.....',
    '....KKKKKKKKO...',
    '...KKKKKWKKK....',
    '..KKKK.KKKK.....',
    '..KKK...KKK.....',
    '..K.......K.....',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  // ---- BOSSES (16x16, render-scaled: lion/bear x2, goliath x3) ---------
  lion_1: [
    '................',
    '...KKKKKKK......',
    '..KNNNNNNNK.....',
    '.KNNFFFFFNNK....',
    '.KNFFKFFKFFNK...',
    '.KNFFFFFFFFNK...',
    '.KNNFFKKFFNNK...',
    '..KNNFFFFNNK....',
    '...KKNNNNKKKKK..',
    '..KFFFFFFFFFFK..',
    '.KFFfFFFFfFFFK..',
    '.KFFFFFFFFFFFKK.',
    '.KFfFFFfFFFfFK..',
    '..KKFKKFKKFKK...',
    '..KF..KF..KF....',
    '................',
  ],
  lion_2: [
    '................',
    '...KKKKKKK......',
    '..KNNNNNNNK.....',
    '.KNNFFFFFNNK....',
    '.KNFFKFFKFFNK...',
    '.KNFFFFFFFFNK...',
    '.KNNFFKKFFNNK...',
    '..KNNFFFFNNK....',
    '...KKNNNNKKKKK..',
    '..KFFFFFFFFFFK..',
    '.KFFfFFFFfFFFK..',
    '.KFFFFFFFFFFFKK.',
    '.KFfFFFfFFFfFK..',
    '...KFKKFKKFKK...',
    '....FK..FK..F...',
    '................',
  ],
  bear_1: [
    '................',
    '................',
    '..KK......KK....',
    '.KNNK....KNNK...',
    '.KNNNKKKKNNNK...',
    '.KNNNNNNNNNNK...',
    '.KNKNNNNNKNNK...',
    '.KNNNnKKnNNNK...',
    '..KNNNnnNNNK....',
    '.KNNNNNNNNNNKK..',
    'KNNnNNNNNNnNNNK.',
    'KNNNNNNNNNNNNNK.',
    'KNnNNNNNNNNNnNK.',
    '.KKNNKKKKKNNKK..',
    '..KNK....KNK....',
    '................',
  ],
  bear_2: [
    '................',
    '................',
    '..KK......KK....',
    '.KNNK....KNNK...',
    '.KNNNKKKKNNNK...',
    '.KNNNNNNNNNNK...',
    '.KNKNNNNNKNNK...',
    '.KNNNnKKnNNNK...',
    '..KNNNnnNNNK....',
    '.KNNNNNNNNNNKK..',
    'KNNnNNNNNNnNNNK.',
    'KNNNNNNNNNNNNNK.',
    'KNnNNNNNNNNNnNK.',
    '.KKNNKKKKKNNKK..',
    '...KNK..KNK.....',
    '................',
  ],
  goliath_1: [
    '....KKKKKK......',
    '...KEEEEEEK.....',
    '...KEEEEEEKK....',
    '...KSSSSSSK.....',
    '...KSKSSKSK.....',
    '...KSSSSSSK.....',
    '....KSnnSK......',
    '...KEEEEEEK.....',
    '..KEeEEEEeEK....',
    '..KEEEEEEEEK....',
    '..KEeEEEEeEK....',
    '..KEEEEEEEEK....',
    '...KeeK.KeeK....',
    '...KeeK.KeeK....',
    '...KKKK.KKKK....',
    '................',
  ],
  goliath_2: [
    '....KKKKKK......',
    '...KEEEEEEK.....',
    '...KEEEEEEKK....',
    '...KSSSSSSK.....',
    '...KSKSSKSK.....',
    '...KSSSSSSK.....',
    '....KSnnSK......',
    '...KEEEEEEKS....',
    '..KEeEEEEeEKS...',
    '..KEEEEEEEEK....',
    '..KEeEEEEeEK....',
    '..KEEEEEEEEK....',
    '...KeeK.KeeK....',
    '...KeeK.KeeK....',
    '...KKKK.KKKK....',
    '................',
  ],
  spear: [ // Goliath's projectile (16x16, points RIGHT)
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '.............K..',
    '.NNNNNNNNNNNNKK.',
    '.............K..',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
};
